# Generated by Django 5.2 on 2026-02-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
