# Generated by Django 5.2 on 2026-02-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0002_reel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
