# Generated by Django 5.2 on 2026-02-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0003_alter_reel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reels.reel')),
            ],
            options={
                'unique_together': {('reel', 'ip_address')},
            },
        ),
    ]
