# Generated by Django 5.2 on 2026-02-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0005_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
