# Generated by Django 5.2 on 2026-02-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0007_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='created_at',
        ),
    ]
