# Generated by Django 5.2 on 2026-02-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0009_view_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='created_at',
            new_name='watched_at',
        ),
    ]
