# Generated by Django 5.2 on 2026-02-16 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0010_rename_created_at_view_watched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
