# Generated by Django 5.2 on 2026-02-19 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0011_alter_view_watched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
